version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_DATABASE=zf_notification
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_HOST=db
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    container_name: php73
    depends_on:
      - db

  db:
    image: mysql:5.7
    networks:
      - backend
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_DATABASE=zf_notification
    container_name: mysql5
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    networks:
      - backend
    restart: always
    ports:
      - "30006:80"
    environment:
      - PMA_HOST=mysql5
      - PMA_PORT= 3306
    container_name: phpmyadmin-app

networks:
  frontend:
  backend:
volumes:
  mysql_data: { driver: local }
