<div style="margin:0;padding:0;min-width:100%;background-color:#ffffff;">
	<div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;"></div>
        <p>Hi ,<br> 
                    Welcome to <span>Inpera Team</span>!</p>
	<table width="100%" border="0" cellpadding="0" cellspacing="0" style="min-width: 100%;" role="presentation">
		<tr> 
                    <td align="center">
                        <div>
                            <h3><?=$this->message;?></h3>
                        </div>
                    </td>
		</tr>
	</table>
</div>
