<div class="container" id="app">
    <!-- show error message by using VueJS -->
    <p v-if="errors.length">
        <ul>
            <li v-for="error in errors">{{ error }}</li>
        </ul>
    </p>
    
    <?php
        $flash = $this->flashMessenger();
        echo $flash->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
        echo $flash->render('info', ['alert', 'alert-dismissible', 'alert-info']);
        echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-warning']);
        echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success']);
    ?>
    
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 offset-sm-1 text-center">
            <h1>Notification Application</h1>
            <hr>
            <form class="subscriber" @submit="Form1" action="<?php echo $this->url('subscriber'); ?>" method="post">
                <div class="form-group row">
                    <label for="email" class="col-sm-2 col-form-label">Recipient</label>
                    <div class="col-sm-6">
                        <input type="text" id="email" class="form-control" name="email" v-model="email">
                    </div>
                    <input type="submit" class="notify" name="submit" value="Subscribe to notifications" />
                </div>
            </form>
            <form name="contact-form" @submit="Form2" action="<?php echo $this->url('notify'); ?>" method="post">
                <div class="form-group row">
                    <label for="message" name="message" class="col-sm-2 col-form-label">Message</label>
                    <div class="col-sm-6">
                        <textarea id="message" name="message" class="form-control" v-model="message"></textarea>
                    </div>
                    <input type="submit"  class="notify" name="submit" value="Notify subscribers with message" />
                </div>
            </form>
        </div>
    </div>
</div>
<!--VueJS code for form validation -->
<script>
const app = new Vue({
    el: '#app',
    data: {
        errors: [],
        email: null,
        message: null
    },
    methods: {
        Form1: function (e) {
            this.errors = [];
            if (!this.email) {
                this.errors.push('Email required.');
            } else if (!this.validEmail(this.email)) {
                this.errors.push('Valid email required.');
            }

            if (!this.errors.length) {
                return true;
            }

            e.preventDefault();
        },
        Form2: function (e) {
            if (this.message) {
                return true;
            }
            this.errors = [];

            if (!this.message) {
                this.errors.push('Message required.');
            }
            e.preventDefault();
        },
        validEmail: function (email) {
            var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
            return re.test(email);
        }
    }
})
</script>


